### ISSUE TITLE
How to set email from address

### ISSUE THREAD

**Issue by boncey** [Tripwire/tripwire-open-source#13]
Hi, I'm running tripwire on a server and it's been working well for years.
It was configured to deliver emails to a local address but I've recently changed it to deliver to an external email provider (via a local alias).

That provider is now rejecting the emails as they don't have a fully-qualified sender address.
For some reason the emails are sent with a from address that is just `tripwire@machine_name`, with no domain.
I've checked all my config and there is no reference to that address.
All my `emailto` values in my policy file are fully qualified.

Is there a way that I can configure that address please?

 Thanks, Darren.

**Comment by brc0x1** [comment]
Hi Darren, a lot of people have asked for this, so I added a new MAILFROMADDRESS config file option in version 2.4.3.0, which lets you specify an address for your "From:" field.  (It still defaults to tripwire@machine_name if you don't specify a value).

**Comment by boncey** [comment]
Thanks for that, will upgrade and use that setting.
