### ISSUE TITLE
Strange file permissions

### ISSUE THREAD

**Issue by didier13150** [Tripwire/tripwire-open-source#14]
Hi,

First thanks for your application.

2 cpp files have executable permissions:
* src/db/hierdatabase.cpp
* src/core/codeconvert.cpp

Best regards,

Didier.

**Comment by brc0x1** [comment]
Ok, thanks, I've fixed this on a new dev/2.4.3.3 branch.  Current plan is to merge it as soon as I've got issue #15 fully sorted out.

**Comment by brc0x1** [comment]
Fixed in 2.4.3.3, so closing this issue.

**Comment by didier13150** [comment]
Thank you.
