### ISSUE TITLE
how & why should i use this package?

### ISSUE THREAD

**Issue by cdaringe** [Tripwire/tripwire-open-source#17]
the README is rather minimal.  im interested, but there's not enough info to digest whether or not this is a good option for me!

**Comment by cdaringe** [comment]
no response, just closed?

**Comment by merces** [comment]
Hi! Tripwire is a tool to detect changes in files. You can install it in a Linux box and see its manual page for instructions on how to use. Also, if you google for “tripwire how to” you’ll find lots of tutorials on how to configure it for the first time.

Debian GNU/Linux package description: https://packages.debian.org/en/stretch/tripwire

Bye. o/

**Comment by brc0x1** [comment]
Resolved in 2.4.3.7
