### ISSUE TITLE
2.4.3.3: "twprint --print-report -t 2" does not list affected files

### ISSUE THREAD

**Issue by cboldt** [Tripwire/tripwire-open-source#19]
I have a filesystem with a handful of changes and a handful of errors (missing files that were specifically listed by the policy), and the "-t 2" level of report detail does not give the names of the affected/changed files.  The File System Errors are reported, and the summary section reports how many files have been modified/added.

The "-t 1" and "-t 3" levels correctly report the affected filenames, and for "-t 3", the specific reason or reasons for reporting the file.

2.4.3.2 works as expected.

I've preserved the .twr file.  It is not encrypted and you should be able to reproduce this for yourself.  Let me know if you want a copy.

**Comment by brc0x1** [comment]
Hi, thanks for reporting this. I apparently broke this in 2.4.3.3 while chasing lint warnings, and I have a fix on a new dev/2.4.3.4 branch, if you feel like trying it out.  I should have this merged to master as soon as I track down a 'make install-strip' issue.

**Comment by cboldt** [comment]
Thank you.  I manually made the changes to textreportviewer.cpp, it works here.  Best of luck resolving that "make install-strip" thing.

**Comment by brc0x1** [comment]
Ok, this fix is now merged to master.

**Comment by cboldt** [comment]
Thanks again.  Installed and tested on three different machines, works as expected.
