### ISSUE TITLE
tarball naming

### ISSUE THREAD

**Issue by bdubbs** [Tripwire/tripwire-open-source#22]
github by default creates tarballs like 2.4.3.4.tar.gz.  If a user is downloading the file via a browser, it is translated to a proper file name like tripwire-open-source-2.4.3.4.tar.gz.

If users want to fetch the file via wget of curl, this translation does not work.  This is especially a problem if users want to download a set of programs using a list of urls.

Please set up a link so a user can fetch a properly named tarball using wget without the need to specify  a  -O option.  See for example https://github.com/logrotate/logrotate/releases

  -- Bruce Dubbs
     linuxfreomscratch.org

**Comment by brc0x1** [comment]
Hi, thanks for pointing this out; I didn't realize this was a problem. I've updated the Releases page with curl/wget-friendly copies of the 2.4.3.4 source bundles.

**Comment by bdubbs** [comment]
Perfect.  Thank you.

**Comment by bdubbs** [comment]
Can you please update the Release page as above for the  2.4.3.5 source bundles.  Thanks.

**Comment by brc0x1** [comment]
D'oh, I knew I was forgetting something.  Done now.  I'll put this on my release checklist so hopefully I'll remember next time.  :)

**Comment by bdubbs** [comment]
Thank you again.
