### ISSUE TITLE
Need installation instructions

### ISSUE THREAD

**Issue by tobiasfielitz** [Tripwire/tripwire-open-source#26]
Would be great if you'd have some simple instructions how to install from source.

Attempt:

```
git clone <repo>
./touchconfig.sh
./configure
make
./installer/install.sh /root/tripwire-open-source/installer/install.cfg -n -f -s abc123 -l 123abc
```

Gives me:

```
Error: configuration parameter $TWPOLICY undefined.
There is an error in the configuration file /root/tripwire-open-source/installer/install.cfg.
```

**Comment by brc0x1** [comment]
Hi Tobias, you probably want to try a "make install" instead.  In install.cfg, $TWPOLICY gets set to the value of the gmake variable $sysconfdir, which will be blank if you invoke the install.sh script directly.

**Comment by tobiasfielitz** [comment]
What is install.sh for?

**Comment by brc0x1** [comment]
install.sh is invoked by make install, and it handles the interactive parts of setting up OST.  It wouldn't be hard to tweak install.sh / install.cfg so various variables (sysconfdir, prefix, path_to_vi etc.) have useful defaults if you run the script directly, but that's not how it works at the moment.

**Comment by brc0x1** [comment]
Ok, I went ahead & updated install.sh to ensure that those variables get set, so the script should work the way you expected it to.  The change is on the dev/next branch ( https://github.com/Tripwire/tripwire-open-source/tree/dev/next ), which should become OST 2.4.3.6 in the near future.

**Comment by tobiasfielitz** [comment]
Awesome, thanks!
