### ISSUE TITLE
Explain return code in man page

### ISSUE THREAD

**Issue by didier13150** [Tripwire/tripwire-open-source#28]
Hi there,
I need some information about return code. I try to look into code, but it's very difficult to have a complete list. It will be very nice to add this in man page.
Thank in advance,
Didier.

**Comment by brc0x1** [comment]
Hi Didier, I was surprised to realize the man pages don't document return codes. They absolutely should do this, and I'll fix this in the next release.  Until then, here's a quick summary of how things are intended to work:

* The _twadmin_, _twprint_, and _siggen_ commands return 0 on success, and 1 on any error.

* In _tripwire_ integrity check mode, the return code is a set of bits OR'd together to indicate the check result:
1:  At least one file or directory was added.
2: At least one file or directory was removed.
4: At least one file or directory was modified.
8: At least one error occurred during the check.
So if an integrity check returns 0, it means the check ran successfully and no changes were observed.

* Other _tripwire_ modes return 0 on success, and 8 on error, for consistency with IC mode.

Right now there might be an exception or two to these rules; I see one spot in core/msystem.cpp that would exit with -1, but it's right below a comment saying "should never happen ...", and I doubt anyone will bump into it in practice. I think I'll change this and any other exceptions I run across at the same time I update the man pages.

**Comment by didier13150** [comment]
thank you brian. Have you a date for the next release ?

**Comment by brc0x1** [comment]
I don't have an exact date, but it will probably be sometime in December or January.

**Comment by brc0x1** [comment]
I've added Exit Code sections to the man pages on this branch: https://github.com/Tripwire/tripwire-open-source/tree/dev/q1-2018 .  I have some other documentation stuff to do there before it becomes a 2.4.3.7 release, but I hope to have that wrapped up in the near future.

**Comment by brc0x1** [comment]
Resolved in 2.4.3.7

**Comment by brc0x1** [comment]
Closing as resolved.
