### ISSUE TITLE
Filename: /usr/local/etc/tw.cfg

### ISSUE THREAD

**Issue by Turtle-Sec** [Tripwire/tripwire-open-source#32]
Hi, 
i have a problem when i run "tripwire --init". In fact, I have this error : 

user@ubuntu:/etc/tripwire$ tripwire --init
### Exiting...

I don't know with tripwire try access to /usr/local/etc/tw.cfg whereas my config file is in /etc/tripwire 

Thanks for help :)

**Comment by brc0x1** [comment]
Hi there, the problem you're running into is that OST's default behavior is to look for a tw.cfg in /usr/local/etc, not in the current directory.  There are two approaches you can take here:
* You can specify a cfg location on the command line, which overrides the default location: "./tripwire --init --cfgfile /etc/tripwire/tw.cfg" in your case.  
* If you don't like having to do that all the time, you can specify a different default location at compile time.  To look in /etc/tripwire by default, configure with "./configure --sysconfdir=/etc/tripwire" and then make the project as usual.  (You could also do this with "./configure --prefix=/etc/tripwire", which is what the readme currently says to do, but that also changes the install location to /etc/tripwire, which you probably don't want.)

**Comment by brc0x1** [comment]
There shouldn't be any problems with relocating your config file to /etc or some other location if you'd rather have it there.  I've even heard of people storing their OST binaries, data, & config files on a thumb drive so they're only present on the system when doing a scan.

**Comment by Turtle-Sec** [comment]
OK thanks

**Comment by brc0x1** [comment]
Closing as resolved.
