### ISSUE TITLE
Compile issue on Centos 7

### ISSUE THREAD

**Issue by PhilipPeake** [Tripwire/tripwire-open-source#4]
g++ -DHAVE_CONFIG_H		  -I.. -I../..    -O -pipe -Wall -Wno-non-virtual-dtor -c -o integer.o integer.cpp
integer.cpp: In function ‘void MontgomeryReduce(word*, word*, const word*, const word*, const word*, unsigned int)’:
integer.cpp:743:8: warning: unused variable ‘carry’ [-Wunused-variable]
   word carry = Add(R, R, M, N);
        ^
integer.cpp: In function ‘void CorrectQuotientEstimate(word*, word*, word&, word&, const word*, unsigned int’:
integer.cpp:903:7: warning: unused variable ‘borrow’ [-Wunused-variable]
  word borrow = Subtract(R, R, T, N+2);
       ^
integer.cpp: In member function ‘Integer& Integer::operator++()’:
integer.cpp:1617:8: warning: unused variable ‘borrow’ [-Wunused-variable]
   word borrow = Decrement(reg, reg.size);
        ^
In file included from modarith.h:9:0,
                 from integer.cpp:5:
algebra.h: In instantiation of ‘T AbstractEuclideanDomain<T>::Gcd(const Element&, const Element&) const [with T = Integer; AbstractEuclideanDomain<T>::Element = Integer]’:
integer.cpp:2111:46:   required from here
algebra.h:276:35: error: ‘Equal’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  while (!Equal(g[i1], this->Zero()))
                                   ^
algebra.h:276:35: note: declarations in dependent base ‘AbstractGroup<Integer>’ are not found by unqualified lookup
algebra.h:276:35: note: use ‘this->Equal’ instead

**Comment by brc0x1** [comment]
Hi, the 2.4.3.0 update fixes this compilation issue.
