### ISSUE TITLE
Unable to run Tripwire

### ISSUE THREAD

**Issue by ausilianapoli** [Tripwire/tripwire-open-source#41]
Hi, I have installed tripwire on Linux Mint 19.1 following these instructions:
`./touchconfig.sh`
`./configure`
`make`
And I don't have error messages; I have executed `make check` successfully, too.
But if I wrote `./tripwire --init` or `./twadmin --generate-keys -L /etc/tripwire/${HOSTNAME}-local.key ` I have the message error `bash: ./twadmin (or ./tripwire): File o directory doesn't exist`.
Why? How could I resolve it?
Thanks.

**Comment by brc0x1** [comment]
Hi Maria, by default OST binaries should be in the 'bin' directory below your main checkout directory.  So if you cloned the repo to ~/tripwire-open-source, executables will be in ~/tripwire-open-source/bin.

**Comment by ausilianapoli** [comment]
Thanks, problem fixed!
Tips: add more info to installation guide.
