### ISSUE TITLE
tripwire double

### ISSUE THREAD

**Issue by tvjams** [Tripwire/tripwire-open-source#45]
sh&££€&

&

e
r

f
d
f
g
h
h
f

f
f
f
f
g
g
g
g
h
h

hh
h

h
hh

g
h
h
h
h
h

gh
h
h

h
h
h
h
h
h
h
h
h
h
h

h
h
h

h
h

a

aa
a
a
a
a
a
a

G
G

G

D
E
F
G
G

S
D
G
H
H
H
J
Y

HY
R
S
S
G
H
J
J

JH
D

RT
H

D
S

t
hb

b
g
u
h
g
d
w
w
g
h

n
m
mm

nh
b
f
e

w
s
d
t
g

dd
d
d
s
s
s
a

a
sa
s

d
f
f
d
d
.

**Comment by brc0x1** [comment]
Closing as "Submitted by Keyboard Cat"
