### ISSUE TITLE
Tripwire reporting multiple errors on system date change

### ISSUE THREAD

**Issue by ilgold** [Tripwire/tripwire-open-source#46]
Hi,
I am using tripwire-2.4.3.7   on CentOS7.8.
Following steps provided in the tripwire instructions created both keys, config and policy files and initialised the database.
Running tripwire --check reports no errors as expected.
Then had to change system date by moving +2 days forward.
Running tripwire --check reports multiple errors indicating that all files are modified.
Obviously no files were modified on the system. 
As far as I understood tripwire check will compare every file hash against a record in the database for file integrity including permissions.
How the system time can affect this check? No file has changed after moving system date forward.
I am interested to understand what can cause this kind of error reported by tripwire?
I am happy to provide more info if needed.

**Comment by didier13150** [comment]
Hi,
I'm the current epel package maintainer and this behaviour depends of security level you set for this file in your config, (aka what kind of check must be done): SEC_CRIT, SEC_SUID, SEC_BIN, SEC_CONFIG, SEC_LOG, SEC_INVARIANT, SIG_LOW, SIG_MED, SIG_HI.

Tripwire can check modifications about content, ctime, mtime, etc... and even selinux tags (if enabled).

Type ```man twpolicy``` to list exhaustive list of what check can be done.

Cheers,

Didier.

**Comment by ilgold** [comment]
> Hi,
> I'm the current epel package maintainer and this behaviour depends of security level you set for this file in your config, (aka what kind of check must be done): SEC_CRIT, SEC_SUID, SEC_BIN, SEC_CONFIG, SEC_LOG, SEC_INVARIANT, SIG_LOW, SIG_MED, SIG_HI.
> 
> Tripwire can check modifications about content, ctime, mtime, etc... and even selinux tags (if enabled).
> 
> Type `man twpolicy` to list exhaustive list of what check can be done.
> 
> Cheers,
> 
> Didier.

Hello Didier,
Thank you for your prompt response.
I have looked at the twpolicy description which allows to check certain time related elements like:
Access timestamp, Inode timestamp (create/modify) and Modification timestamp.
By the way, none of these should have changed on a specific files by moving the operating system date forward by 2 days.
Let's take a few examples from our policy.
/sbin/modprobe                       -> $(SEC_CRIT) ;
/bin/bash                            -> $(SEC_BIN) ;
/dev/urandom                      -> $(SEC_INVARIANT) ;

I am trying to get my head around a question, why would these files suddenly be marked as "Modified" if the operating system date is changed? These files were not modified or re-written in any way.
Is there a more detailed way to check why Tripwire decides that a specific file has to be marked as "Modified"?

**Comment by ilgold** [comment]
Ok, I think I am on to something which might explain why Tripwire marks all files as "Modified".
It has nothing to do with time shift by the way. The time shift just helped to reproduce the issue ;-)

I have compared the stat information from the same file (/bin/bash) in both cases: no errors on tripwire scan and when it is marked as modified.
The only single difference I've seen is in the Device information.
Device: 807h/2055d - all good, no errors reported by tripwire.
Device: 817h/2071d - file modified error reported by tripwire.

The base scan must have been done with Device: 807h/2055d.
The computer has multiple disks and also SDcard and USB can be plugged in. On restart the Device ID is changing.
It seems that kernel is selecting between /dev/sda; /dev/sdb and /dev/sdc assignment on a semi-random basis.
And it looks like Tripwire detects the Device ID change by reporting all files as Modified.
From one side I do not want start making holes in the Tripwire policy but from another side I do not see an easy solution to this issue.
How that can be resolved to avoid such "false positive" detection by Tripwire? May be someone already had a similar issue?

Thank you in advance.

**Comment by brc0x1** [comment]
Hi ilgold (and thanks Didier for chiming in earlier) -- sorry about the very late reply.   I'm not sure anyone else has reported this, but I do vaguely remember reading about this a while ago, and IIRC you're correct that the kernel doesn't provide stable device numbers for removable media across reboots, though I don't recall exactly why it works this way.  In any case, I think you can safely stop monitoring the device number attribute since it's causing so much noise, by adding a "-d" to the appropriate attribute masks in your policy file (or just removing a "+d" if it's being added that way).  Especially if you're still monitoring the inode number, since I can't immediately think of a scenario where a malicious change (or some other sort of "real" change) would manifest as just the device number and nothing else changing.  

-b

**Comment by brc0x1** [comment]
Closing as this seems to be resolved and the issue has gone a few months without any further activity.
